[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["JunBumHan<2hanjunbum6@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
